/*게시판*/
DROP TABLE BOARD;
DROP SEQUENCE BOARDSEQ;

CREATE SEQUENCE BOARDSEQ;
CREATE TABLE BOARD(
B_NO NUMBER PRIMARY KEY,
U_ID VARCHAR2(50) REFERENCES USERS(U_ID) NOT NULL,
B_TITLE VARCHAR2(255) NOT NULL,
B_CONTENT VARCHAR2(2000) NOT NULL,
B_DATE DATE NOT NULL,
B_HITS NUMBER NOT NULL
)
SELECT * FROM BOARD;

SELECT B_NO,U_ID,B_TITLE,B_CONTENT,B_DATE,B_HITS,(SELECT U_GRADE FROM USERS WHERE U_ID=B.U_ID)AS U_GRADE FROM BOARD B WHERE B_NO=163

INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);
INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL,'test','test','test',SYSDATE,0);





select * from(select rownum as rn, A.b_no,A.u_id,A.b_title,A.b_content,A.b_date,A.B_hits from(select rownum,b_no,u_id,b_title,b_content,b_date,B_hits from board order by b_no desc)A
 where rownum<=10)
where rn>=1;

SELECT COUNT(*) FROM BOARD

SELECT * FROM(SELECT ROWNUM AS RN,A.B_NO,A.U_ID,A.B_TITLE,A.B_CONTENT,A.B_DATE,A.B_HITS,TOTAL,U_GRADE FROM
(SELECT ROWNUM,B_NO,U_ID,B_TITLE,B_CONTENT,B_DATE,B_HITS,
(SELECT COUNT(*) FROM ANSWER WHERE B_NO=B.B_NO)AS TOTAL, (SELECT U_GRADE FROM users WHERE U_ID=B.U_ID)AS U_GRADE FROM BOARD B ORDER BY DECODE(U_ID, 'admin1234', U_ID), B_NO DESC)A
WHERE ROWNUM <=1*10)
WHERE 1*10-9 <=RN

SELECT *FROM BOARD

/*댓글 게시판*/
DROP TABLE ANSWER;
DROP SEQUENCE ANSWERSEQ;

CREATE SEQUENCE ANSWERSEQ;
CREATE TABLE ANSWER(
A_NO NUMBER PRIMARY KEY,
B_NO NUMBER REFERENCES BOARD(B_NO) ON DELETE CASCADE,
U_ID VARCHAR2(50) NOT NULL,
A_CONTENT VARCHAR2(1000) NOT NULL,
A_DATE DATE NOT NULL,
A_EN VARCHAR2(2) NOT NULL,
A_PNO NUMBER NULL,
CONSTRAINT ANSWER_EN CHECK(A_EN IN ('Y','N'))
)
INSERT INTO ANSWER VALUES(101,78,'test','a',SYSDATE,'Y',99)

SELECT*FROM ANSWER
SELECT LEVEL,A_NO,B_NO,U_ID,A_CONTENT,A_DATE,A_EN,A_PNO, (SELECT U_ID FROM ANSWER B WHERE B.A_NO=A.A_PNO)AS PNO_ID
	FROM ANSWER A WHERE B_NO=78
	START WITH A_PNO IS NULL
	CONNECT BY PRIOR A_NO=A_PNO
	ORDER SIBLINGS BY A_NO DESC

SELECT * FROM BOARD WHERE B_title LIKE '11' || '%'

SELECT * FROM
(SELECT ROWNUM AS RN,A.B_NO,A.U_ID,A.B_TITLE,A.B_CONTENT,A.B_DATE,A.B_HITS 
FROM
(SELECT ROWNUM,B_NO,U_ID,B_TITLE,B_CONTENT,B_DATE,B_HITS FROM BOARD WHERE UPPER(U_ID) LIKE '%' || UPPER('test') || '%' ORDER BY B_NO DESC)A
WHERE ROWNUM <=1*10)
WHERE 1*10-9 <=RN

SELECT LEVEL,A_NO,B_NO,U_ID,A_CONTENT,A_DATE,A_EN,A_PNO
	FROM ANSWER WHERE B_NO=78
	START WITH A_PNO IS NULL
	CONNECT BY PRIOR A_NO=A_PNO
	ORDER SIBLINGS BY A_NO DESC
	
	SELECT LEVEL AS LV,A_NO,B_NO,U_ID,A_CONTENT,TO_CHAR(A_DATE,'yyyy.MM.dd') A_DATE,A_EN,A_PNO, (SELECT U_ID FROM ANSWER B WHERE B.A_NO=A.A_PNO)AS PNO_ID
	FROM ANSWER A WHERE B_NO=77
	START WITH A_PNO IS NULL
	CONNECT BY PRIOR A_NO=A_PNO
	ORDER SIBLINGS BY A_NO DESC
