DROP TABLE CART;
DROP SEQUENCE CARTSEQ;

CREATE SEQUENCE CARTSEQ;
CREATE TABLE CART(
C_NO NUMBER PRIMARY KEY,
I_ID VARCHAR2(50) REFERENCES INFO(I_ID) NOT NULL,
G_NO NUMBER REFERENCES GOODS(G_NO) NOT NULL,
C_AMT NUMBER NOT NULL
)

INSERT INTO CART VALUES(123,'test',123,123)

SELECT * FROM CART
SELECT * FROM CART JOIN GOODS USING(G_NO) WHERE I_ID ='admin'