DROP TABLE CATEGORIE;


DROP SEQUENCE CATEGORIESEQ;

CREATE SEQUENCE CATEGORIESEQ INCREMENT BY 10 START WITH 10;
CREATE TABLE CATEGORIE(
CT_NO NUMBER PRIMARY KEY,
CT_NAME VARCHAR2(30) UNIQUE
)

INSERT INTO CATEGORIE VALUES(CATEGORIESEQ.NEXTVAL,'신선식품');
INSERT INTO CATEGORIE VALUES(CATEGORIESEQ.NEXTVAL,'음료');
INSERT INTO CATEGORIE VALUES(CATEGORIESEQ.NEXTVAL,'유제품');
INSERT INTO CATEGORIE VALUES(CATEGORIESEQ.NEXTVAL,'아이스크림');
INSERT INTO CATEGORIE VALUES(CATEGORIESEQ.NEXTVAL,'과자류');
INSERT INTO CATEGORIE VALUES(CATEGORIESEQ.NEXTVAL,'라면');
INSERT INTO CATEGORIE VALUES(CATEGORIESEQ.NEXTVAL,'가공식품');
INSERT INTO CATEGORIE VALUES(CATEGORIESEQ.NEXTVAL,'생활용품');
INSERT INTO CATEGORIE VALUES(CATEGORIESEQ.NEXTVAL,'빵');
INSERT INTO CATEGORIE VALUES(CATEGORIESEQ.NEXTVAL,'담배/주류');

DELETE FROM CATEGORIE WHERE CT_NO=100

SELECT * FROM CATEGORIE;