DROP TABLE GOODS;
DROP SEQUENCE GOODSSEQ;

CREATE SEQUENCE GOODSSEQ;
CREATE TABLE GOODS(
G_NO NUMBER PRIMARY KEY,
CT_NO NUMBER REFERENCES CATEGORIE(CT_NO) NOT NULL,
G_NAME VARCHAR2(30) UNIQUE NOT NULL,
G_PRICE NUMBER NOT NULL
)
SELECT *FROM GOODS
SELECT *FROM GOODS where ct_no=10
SELECT *FROM GOODS WHERE G_NAME LIKE '치킨도시락' || '%'
--신선식품--
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,10,'치킨도시락',3800);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,10,'정성가득비빔밥',3500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,10,'참치마요골드',900);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,10,'뉴전주비빔',900);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,10,'바싹불고기김밥',2000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,10,'치즈스팸김밥',2000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,10,'통새우버거',2500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,10,'상하이치킨버거',2600);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,10,'콘치즈샌드위치',2000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,10,'케이준치킨샌드',2000);

--음료--
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,20,'오란씨깔라만시캔',1000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,20,'지리산하동녹차',2000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,20,'갈아만든배캔',1000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,20,'밀키스요하이워터',1700);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,20,'맑은샘물',800);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,20,'타로밀크티',2000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,20,'레드불캔',2900);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,20,'홈스타일자몽병',1200);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,20,'콜드브루커피',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,20,'칸타타아메리카노',2200);

--유제품--

INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,30,'소화가잘되는우유',1000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,30,'비요트그래놀라',1400);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,30,'그릭플레인',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,30,'미니멜츠더블딸기',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,30,'쥬시쿨자두',1400);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,30,'맛단지바나나우유',1300);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,30,'저지방우유1L',2650);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,30,'바바파파초코',1600);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,30,'방아약콩두유팩',1300);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,30,'바이오요플레백도',1200);

--아이스크림--

INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,40,'하겐다즈그린티',4200);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,40,'돼지콘',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,40,'나뚜루골드키위',9500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,40,'거꾸로수박바',1000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,40,'스크류아이스',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,40,'아이스망고바',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,40,'카라멜모찌콘',2500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,40,'도라에몽엔초바',1200);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,40,'서주아이스주',1000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,40,'베리베리컵',2000);

--과자류--

INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,50,'프레첼솔티카라멜맛',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,50,'눈을감자와사비',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,50,'딸기웨하스',800);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,50,'크라운땅콩샌드',700);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,50,'포카칩불닭맛',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,50,'자일리톨비타C껌',4000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,50,'마이구미복숭아',1000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,50,'키커바녹차맛',1000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,50,'카라멜오리지널',1000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,50,'달구나롤리팝',700);

--라면--

INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,60,'까르보불닭볶음면',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,60,'신라면블랙사발',1600);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,60,'육개장큰사발',1150);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,60,'짜왕',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,60,'오징어짬뽕',1600);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,60,'김치큰사발',1150);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,60,'사리곰탕',1150);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,60,'새우탕큰사발',1150);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,60,'짜파게티큰사발',1150);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,60,'튀김우동큰사발',1150);

--가공식품--

INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,70,'한끼만두김치볶음맛',2900);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,70,'한끼만두갈릭불고기',2900);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,70,'매콤치킨피자',2700);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,70,'옥수수피자',2700);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,70,'피자그라탕',2700);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,70,'비비고한섬만두',4500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,70,'양반전복큰죽',4500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,70,'양반밤단팥죽',3200);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,70,'슬라이스고구마',2000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,70,'바로먹는통고구마',2000);

--생활용품--

INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,80,'차량용듀얼충전기',12000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,80,'C타입충전기',13000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,80,'시바핸드로션',5900);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,80,'검정머리끈3입',1200);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,80,'헤어스프레이250ml',12000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,80,'기모마스크',4000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,80,'터치장갑',8800);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,80,'수면양말',3500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,80,'무릎담요',8900);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,80,'귀이개',2500);

--빵--

INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,90,'허니카스테라',10000);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,90,'카톡체다치즈한입',1500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,90,'카톡초코카스테라',1800);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,90,'초코호떡',1300);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,90,'카페스노우슈2입',2500);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,90,'작익은옥수수빵',1300);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,90,'오버액션미니롤케익',1200);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,90,'원피스팥카라멜빵',1200);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,90,'원피스카라멜호떡',1200);
INSERT INTO GOODS VALUES(GOODSSEQ.NEXTVAL,90,'치즈케익',1200);




SELECT * FROM GOODS;